# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('zipcode', models.CharField(max_length=5, verbose_name='zip cdoe')),
                ('distance', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='distance')),
                ('verify_phone', models.CharField(blank=True, max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('passcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('fb_name', models.CharField(blank=True, max_length=40, verbose_name='Full Buiness Name')),
                ('ac_name', models.CharField(blank=True, max_length=40, verbose_name='Account Contact Name')),
                ('ss_no', models.CharField(blank=True, max_length=40, verbose_name='Fein or Social Security Number if Sole Proprietor')),
                ('bm_addr', models.CharField(blank=True, max_length=40, verbose_name='Business Mailing Address')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('z_code', models.CharField(blank=True, max_length=10, verbose_name='zip code')),
                ('o_phone', models.CharField(blank=True, max_length=20, verbose_name='office phone')),
                ('c_phone', models.CharField(blank=True, max_length=20, verbose_name='cell phone')),
                ('w_phone', models.CharField(blank=True, max_length=20, verbose_name='work phone')),
                ('b_fax', models.CharField(blank=True, max_length=40, verbose_name='business fax')),
                ('zipcode', models.CharField(max_length=5, verbose_name='zip code')),
                ('distance', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='distance')),
                ('verify_phone', models.CharField(blank=True, max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('passcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('passcode', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify_details', to='account.BaseUser')),
            ],
        ),
    ]
