# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ssn',
            field=models.CharField(blank=True, max_length=30, verbose_name='Social Security Number'),
        ),
    ]
